name: nlp-project
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _sysroot_linux-64_curr_repodata_hack=3
  - accelerate=1.7.0
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.11.10
  - aiosignal=1.2.0
  - anaconda-anon-usage=0.4.4
  - archspec=0.2.3
  - arrow-cpp=19.0.0
  - asttokens=3.0.0
  - attrs=24.3.0
  - aws-c-auth=0.6.19
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.25
  - aws-c-io=0.13.10
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.1.51
  - aws-c-sdkutils=0.1.6
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.11.212
  - bitsandbytes=0.45.5
  - blas=1.0
  - boltons=23.0.0
  - boost-cpp=1.82.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.2.25
  - certifi=2025.4.26
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - comm=0.2.2
  - conda=24.11.3
  - conda-content-trust=0.2.0
  - conda-libmamba-solver=24.9.0
  - conda-package-handling=2.3.0
  - conda-package-streaming=0.10.0
  - cryptography=43.0.0
  - cudatoolkit=11.8.0
  - datasets=2.14.4
  - debugpy=1.8.14
  - decorator=5.2.1
  - dill=0.3.7
  - distro=1.9.0
  - exceptiongroup=1.2.2
  - executing=2.2.0
  - expat=2.6.3
  - faiss=1.9.0
  - fmt=9.1.0
  - freetype=2.13.3
  - frozendict=2.4.2
  - frozenlist=1.5.0
  - fsspec=2025.3.2
  - gflags=2.2.2
  - glog=0.5.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - huggingface_hub=0.31.2
  - icu=73.1
  - idna=3.7
  - importlib-metadata=8.6.1
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=9.1.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jinja2=3.1.6
  - jpeg=9e
  - jsonpatch=1.33
  - jsonpointer=2.1
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - kernel-headers_linux-64=3.10.0
  - krb5=1.20.1
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240116.2
  - libarchive=3.7.4
  - libblas=3.9.0
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.9.1
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.3
  - libfaiss=1.9.0
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=14.2.0
  - libgrpc=1.62.2
  - liblapack=3.9.0
  - libmamba=1.5.8
  - libmambapy=1.5.8
  - libnghttp2=1.57.0
  - libnsl=2.0.1
  - libopenblas=0.3.29
  - libpng=1.6.39
  - libprotobuf=4.25.3
  - libsodium=1.0.18
  - libsolv=0.7.24
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libuuid=2.38.1
  - libwebp-base=1.3.2
  - libxcrypt=4.4.36
  - libxml2=2.13.1
  - libzlib=1.2.13
  - llvm-openmp=20.1.5
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.7
  - menuinst=2.1.2
  - mkl=2024.2.2
  - mkl-service=2.4.2
  - mkl_fft=1.3.14
  - mkl_random=1.2.10
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.1.0
  - multiprocess=0.70.15
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - numexpr=2.10.1
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openssl=3.5.0
  - orc=2.0.1
  - packaging=24.1
  - pandas=2.2.3
  - parso=0.8.4
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=24.2
  - platformdirs=3.10.0
  - pluggy=1.0.0
  - prompt-toolkit=3.0.51
  - propcache=0.3.1
  - protobuf=4.25.3
  - psutil=7.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyarrow=19.0.0
  - pybind11-abi=5
  - pycosat=0.6.6
  - pycparser=2.21
  - pygments=2.19.1
  - pysocks=1.7.1
  - python=3.12.2
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python-xxhash=3.5.0
  - python_abi=3.12
  - pytorch=2.3.1
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - re2=2022.04.01
  - readline=8.2
  - regex=2024.11.6
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.32.3
  - ruamel.yaml=0.18.6
  - ruamel.yaml.clib=0.2.8
  - s2n=1.3.27
  - safetensors=0.5.3
  - scikit-learn=1.6.1
  - scipy=1.15.3
  - sentence-transformers=4.1.0
  - setuptools=72.1.0
  - six=1.17.0
  - snappy=1.2.1
  - sqlite=3.45.3
  - stack_data=0.6.3
  - sysroot_linux-64=2.17
  - tbb=2021.8.0
  - tk=8.6.14
  - tornado=6.4.2
  - tqdm=4.66.5
  - traitlets=5.14.3
  - truststore=0.8.0
  - typing-extensions=4.13.2
  - typing_extensions=4.13.2
  - tzdata=2024b
  - urllib3=2.2.3
  - utf8proc=2.6.1
  - wcwidth=0.2.13
  - wheel=0.44.0
  - xxhash=0.8.0
  - xz=5.4.6
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - yarl=1.18.0
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - beautifulsoup4==4.13.4
      - contourpy==1.3.1
      - cycler==0.12.1
      - faiss-cpu==1.11.0
      - filelock==3.18.0
      - fonttools==4.56.0
      - joblib==1.5.0
      - kiwisolver==1.4.8
      - matplotlib==3.10.1
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - pyparsing==3.2.1
      - soupsieve==2.7
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tokenizers==0.21.1
      - torch==2.7.0
      - transformers==4.51.3
      - triton==3.3.0
